# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUEAA.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PUEAA(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 1448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        Form.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.stackedWidget_2Page1 = QtWidgets.QWidget()
        self.stackedWidget_2Page1.setObjectName("stackedWidget_2Page1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.stackedWidget_2Page1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.stackedWidget_2Page1)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setStyleSheet("border:none;\n"
"font:20px;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    margin-right: 8px; /* Margen derecho */\n"
"    text-align: center; /* Iniciar centrado */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando el cursor pasa por encima */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Resalta el borde inferior */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando está enfocado */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Fondo más claro */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Efecto de sombra */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(500, 40))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    margin-right: 8px; /* Margen derecho */\n"
"    text-align: center; /* Iniciar centrado */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando el cursor pasa por encima */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Resalta el borde inferior */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando está enfocado */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Fondo más claro */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Efecto de sombra */\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 20px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    margin-right: 8px; /* Margen derecho */\n"
"    text-align: center; /* Iniciar centrado */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando el cursor pasa por encima */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Resalta el borde inferior */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando está enfocado */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Fondo más claro */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Efecto de sombra */\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    margin-right: 8px; /* Margen derecho */\n"
"    text-align: center; /* Iniciar centrado */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando el cursor pasa por encima */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Resalta el borde inferior */\n"
"}\n"
"\n"
"/* Cambia el estilo cuando está enfocado */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Fondo más claro */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Efecto de sombra */\n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.stackedWidget_2Page1)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 25))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 4px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 18px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setStyleSheet("border:none;")
        self.toolButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/iconos/people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(180, 45))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4C6D8C; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/iconos/anadir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignRight)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(180, 45))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: Center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525C5E; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/iconos/actualizar-flecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 45))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C2185B ; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/iconos/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addWidget(self.frame_4, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(520, 600))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: 1px solid #CCCCCC; /* Borde suave */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    gridline-color: #DDDDDD; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Espaciado de las celdas */\n"
"    border-radius: 2px; /* Bordes redondeados en las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f0f0f0; /* Fondo claro al pasar el mouse */\n"
"    color: #16344D; /* Texto azul al pasar el mouse */\n"
"}\n"
"\n"
"/* Barra de desplazamiento vertical y horizontal */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    \n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    width: 7px; /* Ancho de la barra vertical */\n"
"    height: 7px; /* Alto de la barra horizontal */\n"
"}\n"
"\n"
"/* Manejador de la barra de desplazamiento (el \"handle\") */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #16344D; /* Barra de desplazamiento en azul */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    min-height: 10px; /* Tamaño mínimo de la barra de desplazamiento vertical */\n"
"    min-width: 10px; /* Tamaño mínimo de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"/* Efecto cuando el mouse pasa por encima del manejador */\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #1A4567; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"/* Líneas de los botones de desplazamiento (arriba/abajo o izquierda/derecha) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Quitar los botones de desplazamiento */\n"
"}\n"
"\n"
"/* Flechas de los botones de desplazamiento */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none; /* Quitar las flechas */\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.stackedWidget_2.addWidget(self.stackedWidget_2Page1)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Navbar"))
        self.label.setText(_translate("Form", "Número de Expediente:"))
        self.label_2.setText(_translate("Form", "¿Presento PUEAA?"))
        self.label_3.setText(_translate("Form", "Número de concepto:"))
        self.label_4.setText(_translate("Form", "Fecha de concepto:"))
        self.label_5.setText(_translate("Form", "Número de memorando:"))
        self.label_6.setText(_translate("Form", "Fecha de memorando:"))
        self.pushButton_3.setText(_translate("Form", " Crear"))
        self.pushButton_2.setText(_translate("Form", " Actualizar"))
        self.pushButton.setText(_translate("Form", " Borrar"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Expediente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "PUEAA"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Concepto"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Fecha de cooncepto"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Nueva columna"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fecha de memorando"))
