# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registro(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1552, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        Form.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.stackedWidget_2Page1 = QtWidgets.QWidget()
        self.stackedWidget_2Page1.setObjectName("stackedWidget_2Page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stackedWidget_2Page1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.stackedWidget_2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 150))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.ComboTipoConcecion = QtWidgets.QComboBox(self.frame)
        self.ComboTipoConcecion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboTipoConcecion.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboTipoConcecion.setObjectName("ComboTipoConcecion")
        self.ComboTipoConcecion.addItem("")
        self.ComboTipoConcecion.addItem("")
        self.ComboTipoConcecion.addItem("")
        self.ComboTipoConcecion.addItem("")
        self.ComboTipoConcecion.addItem("")
        self.gridLayout.addWidget(self.ComboTipoConcecion, 2, 3, 1, 1, QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("border:none;\n"
"font:20px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("border:none;\n"
"font:20px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.ComboAreaRegistro = QtWidgets.QComboBox(self.frame)
        self.ComboAreaRegistro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboAreaRegistro.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"    \n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboAreaRegistro.setObjectName("ComboAreaRegistro")
        self.ComboAreaRegistro.addItem("")
        self.ComboAreaRegistro.addItem("")
        self.ComboAreaRegistro.addItem("")
        self.ComboAreaRegistro.addItem("")
        self.gridLayout.addWidget(self.ComboAreaRegistro, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.ListColumnas = QtWidgets.QListWidget(self.stackedWidget_2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListColumnas.sizePolicy().hasHeightForWidth())
        self.ListColumnas.setSizePolicy(sizePolicy)
        self.ListColumnas.setMinimumSize(QtCore.QSize(0, 0))
        self.ListColumnas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ListColumnas.setStyleSheet("QListWidget {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px; /* Espaciado de las celdas */\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    width: 7px; /* Ancho de la barra vertical */\n"
"    height: 7px; /* Alto de la barra horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #16344D; /* Barra de desplazamiento en azul */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    min-height: 10px; /* Tamaño mínimo de la barra de desplazamiento vertical */\n"
"    min-width: 10px; /* Tamaño mínimo de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #1A4567; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Quitar los botones de desplazamiento */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none; /* Quitar las flechas */\n"
"}\n"
"")
        self.ListColumnas.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.ListColumnas.setObjectName("ListColumnas")
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListColumnas.addItem(item)
        self.verticalLayout.addWidget(self.ListColumnas, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.frame_3 = QtWidgets.QFrame(self.stackedWidget_2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.LineBuscador = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineBuscador.sizePolicy().hasHeightForWidth())
        self.LineBuscador.setSizePolicy(sizePolicy)
        self.LineBuscador.setMinimumSize(QtCore.QSize(500, 35))
        self.LineBuscador.setMaximumSize(QtCore.QSize(300, 25))
        self.LineBuscador.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 4px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 18px;\n"
"QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"\n"
"    margin-right: 8px; /* Margen a la derecha de 10px */\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineBuscador.setObjectName("LineBuscador")
        self.horizontalLayout_2.addWidget(self.LineBuscador, 0, QtCore.Qt.AlignHCenter)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.toolButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_2.setStyleSheet("border:none;")
        self.toolButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../assets/iconos/people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.TablaRegistro = QtWidgets.QTableWidget(self.stackedWidget_2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TablaRegistro.sizePolicy().hasHeightForWidth())
        self.TablaRegistro.setSizePolicy(sizePolicy)
        self.TablaRegistro.setMinimumSize(QtCore.QSize(1500, 150))
        self.TablaRegistro.setStyleSheet("QTableWidget {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: 1px solid #CCCCCC; /* Borde suave */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    font-size: 12px; /* Tamaño de fuente */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    gridline-color: #DDDDDD; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Espaciado de las celdas */\n"
"    border-radius: 2px; /* Bordes redondeados en las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f0f0f0; /* Fondo claro al pasar el mouse */\n"
"    color: #16344D; /* Texto azul al pasar el mouse */\n"
"}\n"
"\n"
"/* Barra de desplazamiento vertical y horizontal */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    \n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    width: 7px; /* Ancho de la barra vertical */\n"
"    height: 7px; /* Alto de la barra horizontal */\n"
"}\n"
"\n"
"/* Manejador de la barra de desplazamiento (el \"handle\") */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #16344D; /* Barra de desplazamiento en azul */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    min-height: 10px; /* Tamaño mínimo de la barra de desplazamiento vertical */\n"
"    min-width: 10px; /* Tamaño mínimo de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"/* Efecto cuando el mouse pasa por encima del manejador */\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #1A4567; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"/* Líneas de los botones de desplazamiento (arriba/abajo o izquierda/derecha) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Quitar los botones de desplazamiento */\n"
"}\n"
"\n"
"/* Flechas de los botones de desplazamiento */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none; /* Quitar las flechas */\n"
"}\n"
"")
        self.TablaRegistro.setObjectName("TablaRegistro")
        self.TablaRegistro.setColumnCount(15)
        self.TablaRegistro.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaRegistro.setHorizontalHeaderItem(14, item)
        self.verticalLayout.addWidget(self.TablaRegistro, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.BtnExcel = QtWidgets.QPushButton(self.stackedWidget_2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnExcel.sizePolicy().hasHeightForWidth())
        self.BtnExcel.setSizePolicy(sizePolicy)
        self.BtnExcel.setMinimumSize(QtCore.QSize(200, 45))
        self.BtnExcel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnExcel.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 22px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #388E3C; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../assets/iconos/sobresalir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnExcel.setIcon(icon1)
        self.BtnExcel.setIconSize(QtCore.QSize(24, 24))
        self.BtnExcel.setObjectName("BtnExcel")
        self.verticalLayout.addWidget(self.BtnExcel, 0, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem9)
        self.stackedWidget_2.addWidget(self.stackedWidget_2Page1)
        self.horizontalLayout_3.addWidget(self.stackedWidget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Navbar"))
        self.ComboTipoConcecion.setItemText(0, _translate("Form", "Nuevo elemento"))
        self.ComboTipoConcecion.setItemText(1, _translate("Form", "Nuevo elemento"))
        self.ComboTipoConcecion.setItemText(2, _translate("Form", "Nuevo elemento"))
        self.ComboTipoConcecion.setItemText(3, _translate("Form", "Nuevo elemento"))
        self.ComboTipoConcecion.setItemText(4, _translate("Form", "Nuevo elemento"))
        self.label_2.setText(_translate("Form", "Tipo de Permiso:"))
        self.label.setText(_translate("Form", "Zona:"))
        self.ComboAreaRegistro.setItemText(0, _translate("Form", "Nuevo elemento"))
        self.ComboAreaRegistro.setItemText(1, _translate("Form", "Nuevo elemento"))
        self.ComboAreaRegistro.setItemText(2, _translate("Form", "Nuevo elemento"))
        self.ComboAreaRegistro.setItemText(3, _translate("Form", "Nuevo elemento"))
        __sortingEnabled = self.ListColumnas.isSortingEnabled()
        self.ListColumnas.setSortingEnabled(False)
        item = self.ListColumnas.item(0)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(1)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(2)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(3)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(4)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(5)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(6)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(7)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(8)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(9)
        item.setText(_translate("Form", "Nuevo elemento"))
        item = self.ListColumnas.item(10)
        item.setText(_translate("Form", "Nuevo elemento"))
        self.ListColumnas.setSortingEnabled(__sortingEnabled)
        item = self.TablaRegistro.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(1)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(2)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(3)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(4)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(5)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(6)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(7)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(8)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(9)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(10)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(11)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(12)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(13)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(14)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(15)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(16)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(17)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(18)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(19)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(20)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(21)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(22)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.verticalHeaderItem(23)
        item.setText(_translate("Form", "New Row"))
        item = self.TablaRegistro.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tipo de concesion "))
        item = self.TablaRegistro.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Num Expediente"))
        item = self.TablaRegistro.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Num Documento"))
        item = self.TablaRegistro.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Razon Social"))
        item = self.TablaRegistro.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Num Resolucion"))
        item = self.TablaRegistro.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fecha Resolucion"))
        item = self.TablaRegistro.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Fecha Comunicacion"))
        item = self.TablaRegistro.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Caudal Otorgado"))
        item = self.TablaRegistro.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Vigencia"))
        item = self.TablaRegistro.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Fuente"))
        item = self.TablaRegistro.horizontalHeaderItem(10)
        item.setText(_translate("Form", "PUEAA"))
        item = self.TablaRegistro.horizontalHeaderItem(11)
        item.setText(_translate("Form", "New Column"))
        item = self.TablaRegistro.horizontalHeaderItem(12)
        item.setText(_translate("Form", "New Column"))
        item = self.TablaRegistro.horizontalHeaderItem(13)
        item.setText(_translate("Form", "New Column"))
        item = self.TablaRegistro.horizontalHeaderItem(14)
        item.setText(_translate("Form", "New Column"))
        self.BtnExcel.setText(_translate("Form", " Generar Excel"))
